version: '3.8'
services:
  app:
    platform: linux/amd64
    build: .
#    develop:
#      watch:
#        - path: app/** # Watch all files in the current directory
#          action: sync
    ports:
      - "8000:8000"
    volumes:
      - ${STORAGE_PATH}:/usr/share/storage
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STORAGE_PATH=/usr/share/storage
#      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
#      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DESTINATION_REGISTRY=${DESTINATION_REGISTRY}
      - PYTHONPATH=/app
      - JWT_AUTH_TYPE=${JWT_AUTH_TYPE}
      - JWT_VALIDATION_URL=${JWT_VALIDATION_URL}
      - JWT_ISSUER_URL=${JWT_ISSUER_URL}
      - JWT_GROUPS_KEY=${JWT_GROUPS_KEY}
      - JWT_CLIENT_ID=${JWT_CLIENT_ID}
      - RDM_URL=${RDM_URL}
    depends_on:
      - db
    #command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mdps_catalog
    ports:
      - "5433:5432"

volumes:
  postgres_data: 
