version: '3.8'

services:
  app:
    platform: linux/amd64
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ${STORAGE_PATH}:/usr/share/storage
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STORAGE_PATH=/usr/share/storage
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DESTINATION_REGISTRY=${DESTINATION_REGISTRY}
      - PYTHONPATH=/app
      # AWS Keys
      # 
      #
    depends_on:
      - db
    #command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mdps_catalog
    ports:
      - "5432:5432"

volumes:
  postgres_data: 
