"""empty message

Revision ID: 8f5482000550
Revises: 
Create Date: 2025-05-20 09:11:25.733564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5482000550'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'NOT_FOUND', name='jobstatus'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('artifact_name', sa.String(), nullable=True),
    sa.Column('artifact_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('application_packages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('artifact_name', sa.String(), nullable=True),
    sa.Column('artifact_version', sa.String(), nullable=True),
    sa.Column('cwl_id', sa.String(), nullable=True),
    sa.Column('cwl_version', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('source_repository', sa.String(), nullable=True),
    sa.Column('docker_image', sa.String(), nullable=True),
    sa.Column('cwl_url', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_packages_artifact_name'), 'application_packages', ['artifact_name'], unique=False)
    op.create_index(op.f('ix_application_packages_artifact_version'), 'application_packages', ['artifact_version'], unique=False)
    op.create_index(op.f('ix_application_packages_id'), 'application_packages', ['id'], unique=False)
    op.create_index(op.f('ix_application_packages_namespace'), 'application_packages', ['namespace'], unique=False)
    op.create_table('application_package_tags',
    sa.Column('application_package_id', sa.String(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_package_id'], ['application_packages.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_package_tags')
    op.drop_index(op.f('ix_application_packages_namespace'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_id'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_artifact_version'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_artifact_name'), table_name='application_packages')
    op.drop_table('application_packages')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ### 